### PR TITLE
Add project structures to run in Netbeans 

### PR DESCRIPTION
**Pull request by vucongtuanduong**

### CODE REVIEW

**Comment by vucongtuanduong** [comment]
@PTIT-D22KH/btn_java_24-25t1_nmson

**Review by BuiVannn — APPROVED** [review]
CF

**Review by TINABJan254 — APPROVED** [review]
ok

**Review by nhatzonz — APPROVED** [review]

**Review by PearPn15 — APPROVED** [review]
ok

**Pull request merged**
